name: Unexpected Outbound Calls
on:
  workflow_dispatch:
jobs:
  unexpected-outbound-calls:
    name: UnexpectedOutboundCalls
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - run: "curl https://attacker.com -L  || true"
      - run: "curl https://google.com -L  || true"
      - run: "curl microsoft.com:443  --connect-timeout 5 || true"
      - run: "curl amazon.com:443  --connect-timeout 5 || true"
      steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud
        id: Prisma Cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api2.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}

      
